#!/usr/bin/env node

/**
 * DevDoc Generator Pro - Professional Software Project Documentation Tool
 * 
 * 完整软件开发流程文档生成器
 * 流程：需求分析 → 架构设计 → 详细设计 → 任务分解
 */

import { Command } from 'commander';
import { RequirementAnalyzer } from './analyzers/requirement-analyzer.js';
import { ArchitectureDesigner } from './designers/architecture-designer.js';
import { DetailedDesigner } from './designers/detailed-designer.js';
import { TaskBreakdownGenerator } from './generators/task-breakdown.js';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

const program = new Command();

program
  .name('devdoc-pro')
  .description('Professional software project documentation generator')
  .version('2.0.0')
  .argument('<project-name>', 'Name of the project')
  .argument('<requirements>', 'Initial project requirements description')
  .option('-o, --output <dir>', 'Output directory (relative to project dir)', './output')
  .option('-p, --project <path>', 'Project directory path', './project-docs')
  .option('--interactive', 'Run in interactive mode for requirement collection', false)
  .option('--generate-types <types>', 'Document types to generate (all/design/architecture/tasks)')
  .parse();

const options = program.opts();
const projectName = program.args[0];
const initialRequirements = program.args[1];

class ProjectGenerator {
  constructor(config) {
    this.projectName = config.projectName;
    this.requirements = config.requirements;
    this.outputDir = config.outputDir;
    this.projectPath = config.projectPath;
    this.generatedData = {};
  }

  async run() {
    console.log(`\n🚀 DevDoc Generator Pro - Professional Edition`);
    console.log('==============================================');
    console.log(`Project: ${this.projectName}`);
    console.log(`Requirements: ${this.requirements.substring(0, 80)}...`);
    console.log('');

    // Step 1: 需求分析
    console.log('📝 Step 1/4: 需求分析...');
    const requirementAnalyzer = new RequirementAnalyzer(this.requirements);
    const analyzedRequirements = await requirementAnalyzer.analyze();
    this.generatedData.analysis = analyzedRequirements;
    this.writePRD(analyzedRequirements);

    // Step 2: 架构设计
    console.log('🏗️  Step 2/4: 架构设计...');
    const architectureDesigner = new ArchitectureDesigner(analyzedRequirements, {
      projectName: this.projectName,
      requirements: this.requirements
    });
    const architectureDoc = await architectureDesigner.generate();
    this.generatedData.architecture = architectureDoc;
    this.writeArchitectureDocument(architectureDoc);

    // Step 3: 详细设计
    console.log('📋 Step 3/4: 详细设计...');
    const detailedDesignDoc = await this.generateDetailedDesign();
    this.generatedData.detailedDesign = detailedDesignDoc;
    this.writeDetailedDocument(detailedDesignDoc);

    // Step 4: 任务分解
    console.log('📋 Step 4/4: 任务分解...');
    const taskBreakdown = TaskBreakdownGenerator.generate({
      projectName: this.projectName,
      analysis: analyzedRequirements,
      architecture: architectureDoc,
      detailedDesign: detailedDesignDoc
    });
    this.generatedData.tasks = taskBreakdown;
    this.writeTaskBreakdown(taskBreakdown);

    this.generateSummary();

    return this.generatedData;
  }

  writePRD(analysis) {
    const content = `# 📋 产品需求文档 (PRD)

## 项目信息
- **项目名称**: ${this.projectName}
- **生成时间**: ${new Date().toISOString()}
- **版本**: v1.0

---

## 1. 项目目标与背景

### 1.1 项目概述

基于需求："> this.requirements + "

### 1.2 用户画像与使用场景
${this.formatUserStories(analysis.userStories)}

---

## 2. 需求分解

### 2.1 需求分类矩阵

${this.formatRequirementMatrix(analysis.categoryMatrix)}

### 2.2 MoSCoW 优先级排序
${this.formatMoSCoW(analysis.priorityPriorities)}

---

## 3. 功能需求

${this.formatFunctionalRequirements(analysis.functionalRequirements)}
### 非功能需求
${analysis.nonFunctionalRequirements.length > 0 ? analysis.nonFunctionalRequirements.map(nfr => `- **${nfr.category}**: ${nfr.description}`).join('\n') : '未明确指定非功能需求'}

---

## 4. 验收标准

${this.formatAcceptanceCriteria(analysis.acceptanceCriteria)}

---

> 📝 **Generated by DevDoc Generator Pro v2.0.0**
`;

    const prdPath = join(this.outputDir, `${this.projectName.toLowerCase().replace(/\s+/g, '-')}-prd.md`);
    writeFileSync(prdPath, content);
    console.log(`📄 PRD 文档已保存：${prdPath}`);
  }

  writeArchitectureDocument(architectureDoc) {
    const content = `# 🏗️ 架构设计文档

## 1. 系统概览

### 1.1 系统边界
${architectureDoc.systemBoundaries}

### 1.2 核心架构图
\`\`\`mermaid
${architectureDoc.highLevelArchitecture}
\`\`\`

---

## 2. 高级架构设计

### 2.1 分层架构
${this.formatLayers(architectureDoc.layers)}

### 2.2 核心模块划分
${this.formatModules(architectureDoc.coreModules)}

### 2.3 接口定义（高级抽象层）
\`\`\`typescript
${architectureDoc.apiContracts.map(contract => contract.definition).join('\n\n')}
\`\`\`

---

## 3. 技术架构

### 3.1 技术栈选型
${this.formatTechStack(architectureDoc.techStack)}

### 3.2 数据架构
${architectureDoc.dataArchitecture}

### 3.3 部署架构
${architectureDoc.deploymentArchitecture}

---

## 4. 设计决策与约束

${this.formatDecisions(architectureDoc.designDecisions)}

---

> 📋 **Architecture Document - Generated by DevDoc Generator Pro**
`;

    const archPath = join(this.outputDir, `${this.projectName.toLowerCase().replace(/\s+/g, '-')}-architecture.md`);
    writeFileSync(archPath, content);
    console.log(`🏗️ 架构文档已保存：${archPath}`);
  }

  writeDetailedDocument(designDoc) {
    const content = `# 📋 详细设计文档

## 1. 接口实现设计

### 1.1 详细接口定义

${this.formatDetailedInterfaceDefinitions(designDoc.interfaceImplementations)}

---

## 2. 数据模型设计

### 2.1 数据库 Schema
\`\`\`sql
${designDoc.databaseSchema.join('\n')}
\`\`\`

### 2.2 数据流设计
\`\`\`mermaid
${designDoc.dataFlowDiagram}
\`\`\`

---

## 3. 关键算法与逻辑

${this.formatAlgorithmDesigns(designDoc.algorithmDesigns)}

---

## 4. 接口实现规范

### 4.1 代码结构规范
${this.formatCodeStructure(designDoc.structurePatterns)}

### 4.2 错误处理机制
${designDoc.errorHandlingStrategy}

---

> 📋 **Detailed Design Document - Generated by DevDoc Generator Pro**
`;

    const detailedPath = join(this.outputDir, `${this.projectName.toLowerCase().replace(/\s+/g, '-')}-detailed-design.md`);
    writeFileSync(detailedPath, content);
    console.log(`📋 详细设计文档已保存：${detailedPath}`);
  }

  writeTaskBreakdown(tasks) {
    const content = `# 📋 任务分解文档

## Project: **${this.projectName}**
**Generated**: ${new Date().toISOString()}

---

## 整体里程碑

${this.formatMilestones(tasks.milestones)}

---

## 详细任务分解

${tasks.phaseBreakdown.map(phase => `
### ${phase.title}
**阶段目标**: ${phase.description}

#### 任务清单
${phase.tasks.map(task => `- **${task.title}** (${task.estimate}h, ${task.priority})
  - ${task.subTasks?.map(st => `  - ${st}`).join('\n') || ''}`).join('\n')}
`).join('\n')}

---

## 工时与资源

**总工时估算**: ${tasks.totalHours} 小时
**预计工期**: ${tasks.timelineSummary}

### 工作量分布
| 阶段 | 任务数 | 工时 | 百分比 |
|------|--------|------|--------|
${tasks.workloadTable}
---

> 📋 **Generated by DevDoc Generator Pro v2.0.0**
`;

    const tasksPath = join(this.outputDir, `${this.projectName.toLowerCase().replace(/\s+/g, '-')}-tasks.md`);
    writeFileSync(tasksPath, content);
    console.log(`📋 任务任务已保存：${tasksPath}`);
  }

  // ... helper methods ...
}

program.parse();

const main = new ProjectGenerator({
  projectName: program.args[0],
  requirements: program.args[1],
  outputDir: join(process.cwd(), options.output),
  projectPath: join(process.cwd(), options.project)
});

main.run().catch(e => console.error(e));
