#!/usr/bin/env node

/**
 * DevDoc Generator Skill - OpenClaw Skill 版本
 * 支持 CLI 调用、交互模式、启发式问答、自动生成
 * @version 3.0.0
 * @author DevDoc Team
 * @license Apache 2.0
 */

const fs = require('fs');
const path = require('path');

// 📝 全局常量
const APP_NAME = '📄 DevDoc Generator Skill v3.0.0';
const SEPARATOR = '=========================================\n';
const OUTPUT_DIR = './output';

// 📂 工作目录
const WORK_DIR = path.dirname(__filename);
const SKILL_DIR = path.join(WORK_DIR, '../docs/');

/**
 * 🎯 核心功能类
 */
class DevDocGenerator {
  constructor(options = {}) {
    this.projectName = options.projectName || '未命名项目';
    this.requirements = options.requirements || '';
    this.mode = options.mode || 'auto'; // auto, discovery, interactive
    this.outputDir = options.outputDir || OUTPUT_DIR;
    this.interactive = options.interactive || false;
    this.analysis = null;
  }

  // 🎯 启动分析器
  async run() {
    console.log(`\n${APP_NAME}\n${SEPARATOR}`);
    this.logInfo('项目名称', this.projectName);
    this.logInfo('需求描述', this.requirements || '(将在交互中补充)');
    this.logInfo('分析模式', this.getModeLabel(this.mode));
    this.logInfo('输出目录', this.outputDir, '\n');

    // 创建输出目录
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
      console.log('📁 已创建输出目录:', this.outputDir, '\n');
    }

    // 执行需求分析
    console.log('\\n📋 步骤 1/5: 需求分析...\\n');
    this.analysis = await this.analyzeRequirements();
    console.log('✅ 需求分析完成!', '\n');

    // 生成文档
    console.log('\\n📝 步骤 2/5: 生成 PRD 和架构设计...\\n');
    const prd = this.generatePRD();
    const arch = this.generateArchitecture();

    console.log('\\n📝 步骤 3/5: 生成详细设计...\\n');
    const detail = this.generateDetailedDesign();
    writeFileSync('detail', detail);

    console.log('\\n📝 步骤 4/5: 生成任务分解...\\n');
    const tasks = this.generateTasks();

    // 总结
    console.log('\\n✨ 完成!');
    console.log('输出目录:', this.outputDir);
    console.log('文件列表:');
    console.log('- PRD 文档');
    console.log('- 架构设计');
    console.log('- 详细设计');
    console.log('- 任务清单\\n');

    return {
      prd,
      arch,
      detail,
      tasks,
      analysis: this.analysis
    };
  }

  // 🎯 分析需求
  async analyzeRequirements() {
    if (this.mode === 'auto') {
      return this.automaticAnalysis();
    } else if (this.mode === 'discovery') {
      return await this.discoveryAnalysis();
    } else {
      return this.interactiveAnalysis();
    }
  }

  // 🎯 自动分析
  automaticAnalysis() {
    const keywords = ['用户认证', '文档', '编辑器', '协作', '共享', '搜索', '项目', '管理', '权限'];
    const features = keywords.filter(k => this.requirements.includes(k));
    const analysis = {
      projectName: this.projectName,
      timestamp: new Date().toISOString(),
      mode: 'auto',
      features: features.length > 0 ? features : ['用户认证', '文档基础功能', '权限管理', '搜索功能'],
      priority: {
        mustHave: ['用户认证', '文档基础功能', '权限管理'],
        shouldHave: ['搜索功能', '项目协作'],
        couldHave: ['数据统计', '数据分析']
      }
    };
    return analysis;
  }

  // 🎯 启发式分析
  async discoveryAnalysis() {
    // 第一轮：通用问题
    const context = {
      domain: 'general',
      features: [],
      users: [],
      priority: 0
    };

    // 第二轮：针对性问题
    const questions = await this.discoveryQuestions(context);

    return {
      projectName: this.projectName,
      timestamp: new Date().toISOString(),
      mode: 'discovery',
      context: context
    };
  }

  // 🎯 生成 PRD 文档
  generatePRD() {
    const timestamp = this.analysis.timestamp;
    const modeLabel = this.getModeLabel(this.mode);
    const features = this.analysis.features || ['用户认证', '文档基础功能', '权限管理', '搜索功能'];
    const priority = this.analysis.priority || {
      mustHave: ['用户认证', '文档基础功能', '权限管理'],
      shouldHave: ['搜索功能', '项目协作'],
      couldHave: ['数据统计', '数据分析']
    };

    return `# 📋 产品需求文档 (PRD)

## 项目信息
- **项目名称**: ${this.projectName}
- **生成时间**: ${timestamp}
- **分析模式**: ${modeLabel}
- **优先级**: MoSCoW 方法

## 需求概述

基于需求描述生成结构化分析。

## 需求分类

| 模块 | 功能列表 |
|--------|---:|
| 认证模块 | 用户认证 |
| 核心功能 | ${features.join(', ')} |
| 协作功能 | 项目协作 |
| 数据管理 | 数据统计 |

## 功能优先级

### Must Have (必须有)
${priority.mustHave.map(p => '- ' + p).join('\\n')}

### Should Have (应该有)
${priority.shouldHave.map(p => '- ' + p).join('\\n')}

### Could Have (可以有)
${priority.couldHave.map(p => '- ' + p).join('\\n')}

## 用户故事

| 角色 | 功能 | 价值 |
|------|------|------|
| 普通用户 | 进行文档创建和编辑 | 完成日常工作 |
| 系统管理员 | 管理系统和权限 | 保障系统安全 |
| 团队成员 | 参与项目协作 | 提升团队效率 |

## 验收标准

| 要求 | 类型 | 描述 |
|------|------|------|
| 用户认证 | 安全验收 | 登录/注册功能正常工作 |
| 基础功能 | 功能验收 | 文档创建、编辑、权限管理功能正常 |
| 性能要求 | 性能验收 | 核心功能响应<500ms |

---

> 📝 **Generated by DevDoc Generator Skill v3.0.0 - ${this.mode}模式**`;
  }

  // 🎯 生成架构设计
  generateArchitecture() {
    const timestamp = this.analysis.timestamp;

    return `# 🏗️ 技术架构设计

## 项目：${this.projectName}
## 时间：${timestamp}

## 系统架构图

\`\`\`mermaid
graph TB
    subgraph UserLayer[用户层]
        A[Web 前端]
        B[移动客户端]
    end
    
    subgraph GatewayLayer[接入层]
        C[API 网关]
        D[CDN 加速]
        E[负载均衡]
    end
    
    subgraph AppLayer[业务层]
        F[认证服务]
        G[核心业务服务]
        H[数据服务]
        I[通知服务]
    end
    
    subgraph DataLayer[数据层]
        J[(PostgreSQL)]
        K[(Redis)]
        L[(MinIO)]
    end
    
    A --> C
    B --> C
    C --> F
    C --> G
    C --> H
    C --> I
    F --> J
    G --> J
    G --> K
    G --> L
\`\`\`

## 技术栈推荐

### 前端技术
- **框架**: React 18 + TypeScript
- **样式**: Tailwind CSS
- **构建**: Vite
- **状态管理**: Zustand
- **UI 库**: Headless UI

### 后端技术
- **语言**: Node.js + TypeScript
- **框架**: Express.js
- **API 规范**: OpenAPI 3.0
- **验证**: Zod
- **认证**: JWT + bcrypt

### 数据层
- **主数据库**: PostgreSQL (关系型数据)
- **缓存**: Redis (会话、热点数据)
- **存储**: MinIO (对象存储)

### 基础设施
- **容器化**: Docker + Docker Compose
- **部署**: Kubernetes (生产环境)
- **CI/CD**: GitHub Actions
- **监控**: Prometheus + Grafana

## 推荐技术栈依据

- **性能**: 前端静态资源 CDN 加速 + 后端 Redis 缓存
- **扩展性**: 微服务架构，模块化设计，支持水平扩展
- **安全性**: 数据加密传输，敏感信息加密存储，HTTPS 强制

---

> 📋 **Generated by DevDoc Generator Skill v3.0.0**`;
  }

  // 🎯 生成详细设计
  generateDetailedDesign() {
    return `# 📝 详细设计文档

## API 接口设计

### 1. 认证授权接口

\`\`\`typescript
interface AuthService {
  /**
   * 用户登录
   * @param credentials 登录凭证
   * @returns 成功返回 token 信息
   */
  login(credentials: { email: string; password: string }): Promise<TokenResponse>;
  
  /**
   * 用户注册
   * @param userData 用户注册信息
   * @returns 新用户信息及初始 token
   */
  register(userData: RegisterData): Promise<UserWithTokens>;
  
  /**
   * 登出
   * @param token 用户 token
   */
  logout(token: string): Promise<void>;
  
  /**
   * 验证 token
   * @param token 用户 token
   * @returns 用户信息
   */
  validateToken(token: string): Promise<UserProfile>;
  
  /**
   * 刷新 token
   * @param refreshToken 刷新 token
   * @returns 新的 token 对
   */
  refreshToken(refreshToken: string): Promise<TokenPair>;
}
\`\`\`

## 数据库 Schema

\`\`\`sql
-- 用户表
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100),
    is_active BOOLEAN DEFAULT TRUE,
    role VARCHAR(20) DEFAULT 'user',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_active ON users(is_active, created_at);

-- 文档表
CREATE TABLE documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id UUID REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    content JSONB,
    is_deleted BOOLEAN DEFAULT FALSE,
    version INTEGER DEFAULT 1,
    permissions JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_docs_owner ON documents(owner_id);
CREATE INDEX idx_docs_created ON documents(created_at);
\`\`\`

## 错误处理机制

\`\`\`javascript
// App 错误基类
class AppError extends Error {
  constructor(message, statusCode, code) {
    super(message);
    this.statusCode = statusCode;
    this.code = code;
    this.isOperational = true;
  }
}

// 具体错误类型
class ValidationError extends AppError {
  constructor(message) {
    super(message, 400, 'VALIDATION_ERROR');
  }
}

class NotFoundError extends AppError {
  constructor(resource, id) {
    super(\`\${resource} with id \${id} not found\`, 404, 'RESOURCE_NOT_FOUND');
  }
}

// UI 错误处理中间件
app.use((err, req, res, next) => {
  if (err instanceof AppError) {
    return res.status(err.statusCode).json({
      success: false,
      error: {
        code: err.code,
        message: err.message,
        timestamp: new Date().toISOString()
      }
    });
  }
  res.status(50).json({
    success: false,
    error: {
      code: 'INTERNAL_ERROR',
      message: 'Internal server error',
      timestamp: new Date().toISOString()
    }
  });
});
\`\`\`

---

> 📋 **Generated by DevDoc Generator Skill v3.0.0**`;
  }

  // 🎯 生成任务分解
  generateTasks() {
    const timestamp = this.analysis.timestamp;

    return `# 📋 任务分解与工时估算

## 项目信息

- **项目名称**: ${this.projectName}
- **生成时间**: ${timestamp}
- **分析模式**: ${this.mode}
- **总工期**: \~7 周
- **预计工时**: \~280 小时

---

## Phase 1: 基础架构搭建 (Week 1)

**目标**: 项目初始化与环境配置

### 任务清单

#### 1.1 项目初始化
- [ ] 初始化 Git 仓库
- [ ] 配置 ESLint 和 Prettier
- [ ] 设置开发环境脚本
- [ ] 配置 Git hooks

**工时**: \~4 小时

#### 1.2 环境配置
- [ ] npm 包依赖安装
- [ ] 环境变量配置
- [ ] Docker 环境设置
- [ ] CI/CD 流水线配置

**工时**: \~4 小时

#### 1.3 开发工具
- [ ] IDE 配置
- [ ] 调试工具
- [ ] 热重载配置
- [ ] 代码质量工具

**工时**: \~4 小时

**阶段总计**: \~12 小时

---

## Phase 2: 用户认证模块 (Week 2)

**目标**: 实现用户认证与权限管理

### 任务清单

#### 2.1 安全认证
- [ ] 密码加密方案实现 (bcrypt)
- [ ] JWT 令牌系统
- [ ] 会话管理机制
- [ ] 安全配置

**工时**: \~10 小时

#### 2.2 用户管理
- [ ] 用户注册接口
- [ ] 用户登录接口
- [ ] 用户信息管理
- [ ] 用户验证流程

**工时**: \~10 小时

#### 2.3 权限系统
- [ ] 角色定义与权限映射
- [ ] RBAC 权限控制
- [ ] 权限验证中间件
- [ ] 权限配置管理

**工时**: \~8 小时

**阶段总计**: \~28 小时

---

## Phase 3: 核心功能 (Week 2-5)

**目标**: 实现核心业务功能

### 任务清单

#### 3.1 数据库设计
- [ ] ER 图设计
- [ ] Schema 定义
- [ ] 索引优化
- [ ] 数据迁移脚本

**工时**: \~6 小时

#### 3.2 核心 API 实现
- [ ] RESTful API 设计
- [ ] 控制器编写
- [ ] 服务层实现
- [ ] 业务逻辑处理

**工时**: \~30 小时

#### 3.3 前端组件
- [ ] UI 组件库集成
- [ ] 基础页面布局
- [ ] 核心交互逻辑
- [ ] 响应式设计实现

**工时**: \~25 小时

#### 3.4 测试基础
- [ ] 单元测试框架
- [ ] Mock 服务
- [ ] 基础测试用例
- [ ] 集成测试骨架

**工时**: \~12 小时

**阶段总计**: \~73 小时

---

## Phase 4: 辅助功能 (Week 5-7+)

**目标**: 开发辅助业务功能

### 任务清单

#### 4.1 搜索功能
- [ ] 全文搜索引擎
- [ ] 搜索过滤
- [ ] 搜索结果展示
- [ ] 搜索优化

**工时**: \~12 小时

#### 4.2 权限管理
- [ ] 细粒度权限控制
- [ ] 权限配置界面
- [ ] 权限继承机制
- [ ] 权限审计日志

**工时**: \~10 小时

#### 4.3 统计功能
- [ ] 数据统计报表
- [ ] 趋势分析
- [ ] 导出功能
- [ ] 可视化展示

**工时**: \~10 小时

**阶段总计**: \~32 小时

---

## 📊 工时统计

| Phase | 阶段名称 | 任务数 | 工时 (小时) | 时长 |
|------|----------|--------|------|-----|
| 1 | 架构搭建 | 12 | 12 | 1 周 |
| 2 | 认证模块 | 6 | 28 | 1 周 |
| 3 | 核心功能 | 12 | 73 | 4 周 |
| 4 | 辅助功能 | 12 | 32 | 2 周 |
| **总计** | **6 个阶段** | **58** | **217** | **7 周** |

## ⏱️ 开发时间线

```
Week 1:    [===基础架构搭建===]  (12 小时)
Week 2:    [===认证模块实现=====]  (28 小时)  
Week 3-6:  [======核心功能实现======]  (73 小时)
Week 7-8:  [===辅助功能实现=====]  (32 小时)
     周数： 1 | 2 | 3 | 4 | 5 | 6 | 7
```

---

> 📋 **Generated by DevDoc Generator Skill v3.0.0**  
> **版本**: 1.0.0 | **总工时**: \~280 小时 | **总周期**: 7 周`;
  }

  // 🎯 工具函数
  logInfo(label, value, suffix = '\n') {
    console.log(`${label}: ${value}${suffix}`);
  }

  getModeLabel(mode) {
    const modeLabels = {
      'auto': '自动分析',
      'discovery': '启发式问答',
      'interactive': '交互模式'
    };
    return modeLabels[mode] || '未知模式';
  }
}

// 🎯 主程序
async function main() {
  const args = process.argv.slice(2);
  
  // 解析参数
  let config = {
    projectName: '未命名',
    requirements: '',
    mode: 'auto',
    outputDir: './output',
    interactive: false
  };

  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith('--')) {
      const key = args[i].replace('--', '');
      if (!args[i + 1]?.startsWith('-')) {
        config[key] = args[i + 1];
        i++;
      }
    } else if (args[i].startsWith('-')) {
      const key = args[i].replace('-', '');
      if (!args[i + 1]?.startsWith('-')) {
        config[key] = args[i + 1];
        i++;
      }
    } else {
      if (config.projectName === '未命名') {
        config.projectName = args[i];
      } else {
        config.requirements = args.slice(i).join(' ');
      }
    }
  }

  // 创建生成器
  const generator = new DevDocGenerator(config);
  
  // 执行
  await generator.run();
}

// 🎯 运行
main().catch(err => {
  console.error('❌ 错误:', err.message);
  process.exit(1);
});
